//// <auto-generated />
//using Microsoft.Azure.Documents;

//namespace APIDemo.Migrations
//{
//    internal class APIDemoContext
//    {
//        public object User { get; internal set; }

//        internal object Entry(User user)
//        {
//            throw new NotImplementedException();
//        }

//        internal object Entry(User user)
//        {
//            throw new NotImplementedException();
//        }

//        internal Task SaveChangesAsync()
//        {
//            throw new NotImplementedException();
//        }
//    }
//}